<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>os</string>
		<string>osx</string>
	</array>
	<key>comment</key>
	<string>OScript Syntax version 0.0.2</string>
	<key>name</key>
	<string>OScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b\d+(?![eE.0-9])</string>
			<key>name</key>
			<string>constant.numeric.integer.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)?([eE]-?\d*)?</string>
			<key>name</key>
			<string>constant.numeric.float.oscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.oscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.oscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.oscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.oscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.oscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.oscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.begin.oscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.end.oscript</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.oscript</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.oscript</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-slash.oscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.oscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.oscript</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.oscript</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.oscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(?:(\w+)\s+)?(function)\b\s+(\w+)\s+(\w+)</string>
			<key>name</key>
			<string>meta.function.oscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.oscript</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.oscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(script)\b\s+(\w+)</string>
			<key>name</key>
			<string>meta.function.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(break|breakif|by|case|continue|continueif|default|downto|else|elseif|end|endscript|for|goto|if|in|repeat|return|switch|to|until|while)\b</string>
			<key>name</key>
			<string>keyword.control.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(false|none|true|undefined)\b</string>
			<key>name</key>
			<string>constant.language.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(super|this)\b</string>
			<key>name</key>
			<string>variable.language.self.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\$(\w+)\b</string>
			<key>name</key>
			<string>variable.name.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(booleantype|bytestype|datatype|dynamictype|errortype|externtype|integertype|listtype|longtype|objecttype|objreftype|pointtype|realtype|scripttype|stringtype|undefinedtype|voidtype)\b</string>
			<key>name</key>
			<string>support.constant.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(datatypename|echo|echodebug|echoerror|echoinfo|echostamp|echowarn|getfeatures|isdefined|iserror|isfeature|isinvokable|isnoterror|isnotset|isobject|isset|isundefined|length|nparameters|parameters|pointh|pointv|type)\b</string>
			<key>name</key>
			<string>support.function.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(cachetree|capiconnect|capierr|capilog|capilogin|compiler|dapisession|dapinode|dapiversion|dapistream|filecopy|fileprefs|frame|javaobject|mailmessage|pop3session|smtpsession|ssloptions|patfind|patchange|regex|socket|sqlconnection|sqlcursor|uapisession|uapiuser|wapisession|wapimap|wapimaptask|wapiwork|wapisubwork|domattr|domcdatasection|domcharacterdata|domcomment|domdocument|domdocumentfragment|domdocumenttype|domelement|domentity|domentityreference|domimplementation|domnamednodemap|domnode|domnodelist|domnotation|domparser|domprocessinginstruction|domtext|saxparser|xslprocessor)\b</string>
			<key>name</key>
			<string>support.type.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(capi|dapi|env|global|language|logging|math|memcached|otds|pattern|security|sql|str|system|uapi|vis|wapi|web|zip)\b</string>
			<key>name</key>
			<string>support.variable.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(assoc|boolean|bytes|date|dynamic|error|extern|file|integer|interface|list|long|object|package|point|real|recarray|record|script|string|void)\b</string>
			<key>name</key>
			<string>keyword.type.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(final|inherits|private|public|override|using)\b</string>
			<key>name</key>
			<string>storage.modifier.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(and|eq|ge|gt|le|lt|ne|not|or|xor)\b</string>
			<key>name</key>
			<string>keyword.operator.logical.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*=|/=|\+=|\-=</string>
			<key>name</key>
			<string>keyword.operator.assignment.compound.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&amp;=|\^=|\|=</string>
			<key>name</key>
			<string>keyword.operator.assignment.compound.bitwise.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;&lt;|&gt;&gt;|&gt;&gt;</string>
			<key>name</key>
			<string>keyword.operator.bitwise.shift.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>==|!=</string>
			<key>name</key>
			<string>keyword.operator.comparison.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;=|&gt;=|&lt;&gt;|&lt;|&gt;</string>
			<key>name</key>
			<string>keyword.operator.relational.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\!|&amp;&amp;|\|\|</string>
			<key>name</key>
			<string>keyword.operator.logical.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\&amp;|~|\^|\|</string>
			<key>name</key>
			<string>keyword.operator.bitwise.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\=</string>
			<key>name</key>
			<string>keyword.operator.assignment.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%|\*|/|-|\+</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.oscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)#\s*(define|else|endif|ifdef|ifndef|undef)\b</string>
			<key>name</key>
			<string>keyword.preprocessor.oscript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.oscript</string>
	<key>uuid</key>
	<string>DC4FE714-F479-4E59-A7BE-3FF4F356340F</string>
</dict>
</plist>
